language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install -r fiwareglancesync/scripts/getnids/requirements.txt
  - pip install coveralls
  - pip install pep8
  - export GLANCESYNC_SETTINGS_FILE=$(pwd)/fiwareglancesync/app/settings/fiware-glancesync.cfg
  - export GLANCESYNC_LOGGING_SETTINGS_FILE=$(pwd)/fiwareglancesync/app/settings/fiware-glancesync-logging.cfg
  - export GLANCESYNCAPP_CONFIG=$(pwd)/fiwareglancesync/app/config.py

# command to run tests
script:
  - pep8 --max-line-length=120 .
  - nosetests --with-coverage --cover-package=./ --exe

after_success:
  coveralls
